2022-02-15 22:54:16,543 +0000 WARNING _init__:547 — simpleRequest SSL certificate validation is enabled without hostname verification. See: server.conf/[pythonSs1ClientConfig]/sslVerifyServerName. 2022-02-15 22:54:16,543 +0000 ERROR ssl_context:331 — A request to 10.140.178.11 has an invalid certificate at depth 1. OpenSSL error num ber = [19]. Certificate = {'subject': ((('countryName., 'US'),), (('stateOrProvinceName', 'CA'),), (('localityName', 'San Francisco'),), (('organizationName., 'Splunk'),), (('commonNameo, 'SplunkCommonCA'),), (( 'emailAddress., 'support@splunk.com.),)), 'issuer': ((('country Name', .US'),), (('stateOrProvinceName', 'CA'),), (elocalityName., 'San Francisco'),), (( 'organizationName., 'Splunk'),), (('commonNameo , 'SplunkCommonCA'),), WemailAddress., 'support@splunk.com.),)), 'version': 1, 'serialNumber': '8D1C137C1363FC5C3., 'notBefore': 'Jan 30 20:26:54 2017 GMT', 'notAfter': 'Jan 28 20:26:54 2027 GMT., 'basicConstraints.: —1, 'extendedkeyUsage.: 0, 'ex_flags': 8544} 2022-02-15 22:54:16,544 +0000 ERROR __init :569 — SSL error communicating with splunkd (error—[SSL: CERTIFICATE_VERIFY_FAILED] certifica to verify failed: self signed certificate in certificate chain (_ssl.c:1106)), path = https://chieftain:8089 
